checking

diff --git a/.github/workflows/04-dynamic-matrix.yaml b/.github/workflows/04-dynamic-matrix.yaml
--- a/.github/workflows/04-dynamic-matrix.yaml
+++ b/.github/workflows/04-dynamic-matrix.yaml
@@ -1,30 +1,84 @@
-name: Dynamic matrix
+# name: Dynamic matrix
+# on:
+#   workflow_dispatch:
+#     inputs:
+#       length:
+#         description: "Number of foo/bar pairts to generate"
+#         required: true
+#         default: "2"
+# jobs:
+#   generate-matrix:
+#     runs-on: ubuntu-latest
+#     outputs:
+#       include: ${{steps.gen.outputs.include}}
+#     steps:
+#       - name: Generate paired list(foo= random, bar=random)
+#         id: gen
+#         env:
+#           LENGTH: ${{github.event.inputs.length}}
+#         shell: bash
+#         run: |
+#           set -euo pipefail
+
+#           n="${LENGTH: -2}"
+
+#           include_json=$(
+#             {
+#               for (( i=1; i<=n; i++));do
+#                 foo_val=$((RANDOM % 100))
+#                 bar_val=$((RANDOM % 100))
+#                 jq -n -c \
+#                   --argjson foo "$foo_val" \
+#                   --argjson bar "$bar_val" \
+#                   '{foo:$foo, bar:$bar}'
+#               done
+#             } | jq -s -c .
+#           )
+    
+#   execute:
+#     needs: generate-matrix
+#     runs-on: ubuntu-latest
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         include: ${{fromJSON(needs.generate-matrix.outputs.include)}}
+#     steps:
+#       - name: Use matirx values (paired randoms)
+#         run: echo "Matrix - foo=${{ matrix.foo }}, bar=${{ matrix.bar }}"
+
+
+
+############################################################################################3
+name: Dynamic Matrix
 on:
   workflow_dispatch:
     inputs:
       length:
-        description: "Number of foo/bar pairts to generate"
+        description: "Number of foo/bar pairs to generate"
         required: true
         default: "2"
+
 jobs:
   generate-matrix:
     runs-on: ubuntu-latest
     outputs:
-      include: ${{steps.gen.outputs.include}}
+      include: ${{ steps.gen.outputs.include }}
     steps:
-      - name: Generate paired list(foo= random, bar=random)
+      - name: Generate paired list (foo = random, bar = random)
         id: gen
         env:
-          LENGTH: ${{github.event.inputs.length}}
+          LENGTH: ${{ github.event.inputs.length }}
         shell: bash
         run: |
           set -euo pipefail
 
-          n="${LENGTH: -2}"
+          n="${LENGTH:-2}"
 
+          # Generally I would extract this type of logic to a separate
+          # Taskfile task to make it easier to iterate/validate
           include_json=$(
             {
-              for (( i=1; i<=n; i++));do
+              for ((i=1; i<=n; i++)); do
                 foo_val=$((RANDOM % 100))
                 bar_val=$((RANDOM % 100))
                 jq -n -c \
@@ -34,14 +88,17 @@ jobs:
               done
             } | jq -s -c .
           )
-    
+
+          # Output the array for `matrix.include`
+          echo "include=$include_json" >> "$GITHUB_OUTPUT"
+
   execute:
     needs: generate-matrix
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        include: ${{fromJSON(needs.generate-matrix.outputs.include)}}
+        include: ${{ fromJSON(needs.generate-matrix.outputs.include) }}
     steps:
-      - name: Use matirx values (paired randoms)
+      - name: Use matrix values (paired randoms)
         run: echo "Matrix - foo=${{ matrix.foo }}, bar=${{ matrix.bar }}"
